mlr<-lm(Sales~Age+HS+Income+Black+Female+Price,data=Cigarttes)
summary(mlr)
mlr<-lm(MPG~HP+VOL+SP+WT,data=Cars)
summary(mlr)
mrl<-lm(MPG~.,data=Cars)
summary(mrl)
regclass::VIF(mrl)
MASS::stepAIC(mrl,direction = "forward")
MASS::stepAIC(mrl,direction = "backward")
